### ISSUE TITLE
sweep over metrics at the end of the same run

### ISSUE THREAD

**Issue by cmvcordova** [latent-reasoning-works/manylatents#66]
Currently, running multiple values for metrics at the end of the same run is very hacky:

```
defaults:
- _self_
- embedding:
  - _tangent_space_15
  - _tangent_space_25
  - _tangent_space_50
  - _tangent_space_100
  - _tangent_space_250
```

Where each of the sub tangent_space configs contain, at a lower level:

```
tangent_space_15:
  _target_: src.metrics.tangent_space.TangentSpaceApproximation
  _partial_: True
  n_neighbors: 15
  variance_threshold: 0.95
  return_per_sample: True
```

This is a workaround the fact that hydra would instantiate these over values of k, making a new run when specifying a new metric. This is cumbersome as everything has to be instantiated from scratch.

Possible solutions:
Figure out if there's a way to run hydra callbacks at the end of a run only, for multiple values of k. Can probably also be useful in the event of having to aggregate metrics across runs, once they're finalized.
